ebi-ait/ingest-ui

client/src/app/shared/components/project/project.component.html, client/src/app/shared/components/project/project.component.ts, client/src/app/shared/services/ingest.service.ts
Add Delete project button to UI
To address ticket [#18](https://github.com/ebi-ait/hca-ebi-dev-team/issues/18)
=> Delete Project Buton

client/src/app/app.routes.ts, client/src/app/registration/registration.component.html
* Hid registration behind auth guard.
* Added liks to terms and conditions, and privacy policy.
* Updated registration button style.
=> Minor changes to Registration View

client/src/app/app.module.ts, client/src/app/app.routes.ts, client/src/app/navigation/navigation.component.html, client/src/app/project/project.component.ts, client/src/app/welcome/welcome.component.css, client/src/app/welcome/welcome.component.html, client/src/app/welcome/welcome.component.spec.ts, client/src/app/welcome/welcome.component.ts
Implementation of ticket: [#182](https://github.com/ebi-ait/hca-ebi-dev-team/issues/182)
Deployed to [Dev](https://ui.ingest.dev.archive.data.humancellatlas.org)
=> New welcome landing page

client/src/app/template-questionnaire/template-questionnaire-form/template-questionnaire-form.component.html, client/src/app/template-questionnaire/template-questionnaire-form/template-questionnaire-form.component.ts, client/src/app/template-questionnaire/template-questionnaire-form/template-questionnaire-schema.json
Implements ticket [#234](https://github.com/ebi-ait/hca-ebi-dev-team/issues/234)
Added a title to the template questionnaire form page
Changed the introductory text in the template questionnaire form page
Changed the "Generate" button text
=> Questionnaire Text Changes

client/src/app/metadata-schema-form/metadata-form/metadata-form.component.ts, client/src/app/shared/services/broker.service.ts, client/src/app/template-questionnaire/template-generator.service.spec.ts, client/src/app/template-questionnaire/template-generator.service.ts, client/src/app/template-questionnaire/template-questionnaire-form/template-questionnaire-form.component.ts, client/src/app/template-questionnaire/template-questionnaire.data.ts
Implemented methods to call the template generation in the Broker Service
ebi-ait/hca-ebi-dev-team#231
=> Poll for template til it is generated

client/src/app/welcome/welcome.component.html, client/src/app/welcome/welcome.component.ts
Changes:
- Remove the template generation box from the landing page
- Revert back to the previous landing page
- Make additional text changes on the landing page
ebi-ait/hca-ebi-dev-team#279
=> Remove the template generation from the landing page

client/src/app/login/login.component.scss, client/src/app/project-form/project-ingest-schema.json, client/src/app/project-registration/project-registration-summary/project-registration-summary.component.html, client/src/app/welcome/welcome.component.html
Changes:
- Modify text on the landing and project registration page (ebi-ait/hca-ebi-dev-team#279, ebi-ait/hca-ebi-dev-team#300)
- Make the 'Technologies used to generate the data' field required (ebi-ait/hca-ebi-dev-team#299)
=> Change the landing and project registration page

client/src/app/template-questionnaire/answer-key.json, client/src/app/template-questionnaire/default_fields.json
I made some changes to the defaults and answerkey json files to fix some bugs
=> updates to fix linking and logic

client/src/app/template-questionnaire/answer-key.json, client/src/app/template-questionnaire/default_fields.json, client/src/app/template-questionnaire/template-questionnaire.data.ts
- fixed the answer for preNatalQuantity to upper case to make sure it is recognised
- added some links
- removed / added default modules to various specs in the json and in `template-questionnaire.data.ts`
- changed so medical history and height are only added when adult donors are present
=> Fixed some logic and linking

client/src/index.html
Changes:
- Add Google Analytics tracking for Ingest UI - ebi-ait/hca-ebi-dev-team#289
=> Set up Google Analytics for Ingest UI

client/src/app/template-questionnaire/answer-key.json, client/src/app/template-questionnaire/specimen-group/specimen-group.component.ts, client/src/app/template-questionnaire/template-questionnaire-form/template-questionnaire-form.component.ts, client/src/app/template-questionnaire/template-questionnaire-form/template-questionnaire-schema.json, client/src/app/template-questionnaire/template-questionnaire.module.ts
- Redesign logic and linking to ensure correct biomaterials, protocols and link columns are present
- renamed name of downloaded spreadsheet to 'hca_metadata_template_{YYYYMMDD}.xlsx'
- added preNatalQuantity to the initial state of the questionnaire
=> Adjusting Organoid/cell line logic and other fixes

client/src/app/submission/metadata-list/metadata-list.component.html, client/src/app/submission/metadata-list/metadata-list.component.ts, client/src/app/submission/submission.component.html
Modified entity list to indicate whether a biomaterial in the list is linked to other entities or not.
This is part of the work on [issue 41](https://github.com/ebi-ait/dcp-ingest-central/issues/41).
=> Display linking status of biomaterials

client/package.json, client/src/app/app.module.ts, client/src/app/metadata-details-dialog/metadata-details-dialog.component.html, client/src/app/metadata-picker/metadata-picker.component.css, client/src/app/metadata-picker/metadata-picker.component.html, client/src/app/metadata-picker/metadata-picker.component.ts, client/src/app/process-details/process-details.component.css, client/src/app/process-details/process-details.component.html, client/src/app/process-details/process-details.component.spec.ts, client/src/app/process-details/process-details.component.ts, client/src/app/shared/services/ingest.service.spec.ts, client/src/app/shared/services/ingest.service.ts, client/src/app/submission/metadata-list/metadata-list.component.html, client/src/app/submission/metadata-list/metadata-list.component.scss
ebi-ait/dcp-ingest-central#38 (happens in ProcessDetails Component)
ebi-ait/dcp-ingest-central#68 (MetadataPicker Component)
=> Support updating of metadata links

client/src/app/metadata-details-dialog/metadata-details-dialog.component.html, client/src/app/metadata-picker/metadata-picker.component.ts, client/src/app/process-details/process-details.component.html, client/src/app/process-details/process-details.component.ts, client/src/app/submission/metadata-list/metadata-list.component.html
=> Filter metadata picker search result by submission

README.md
added instructions in README.md for adding client id to environment<env>.ts to be able to successfully login
=> Added Instructions on Adding Client ID to Readme

client/src/app/http-interceptors/http-error-interceptor.ts, client/src/app/project/project.component.html, client/src/app/project/project.component.ts, client/src/app/shared/components/data-table/data-source/data-source.ts, client/src/app/shared/components/data-table/data-source/ingest-data-source.spec.ts, client/src/app/shared/components/data-table/data-source/ingest-data-source.ts, client/src/app/shared/components/data-table/data-source/metadata-data-source.spec.ts, client/src/app/shared/components/data-table/data-source/metadata-data-source.ts, client/src/app/shared/components/data-table/data-table.component.html, client/src/app/shared/components/data-table/data-table.component.ts, client/src/app/submission/submission.component.html, client/src/app/submission/submission.component.ts
=> Use datasource for data-table components

client/src/app/shared/models/submissionSummary.ts, client/src/app/shared/services/ingest.service.ts, client/src/app/submission/metadata-data-source.ts, client/src/app/submission/metadata-list/metadata-list.component.html, client/src/app/submission/metadata-list/metadata-list.component.ts, client/src/app/submission/submission.component.html, client/src/app/submission/submission.component.ts
Adds error summary and also simplifies PaginatedDataSource and MetadataDataSource a bit
=> Error summary

client/src/app/submission/submission.component.html
As per @gabsie request in https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/91
=> Only show report if has errors

client/src/app/metadata-details-dialog/metadata-details-dialog.component.ts, client/src/app/metadata-schema-form/custom/vf-tabs/vf-tabs.component.ts, client/src/app/process-details/process-details.component.spec.ts, client/src/app/process-details/process-details.component.ts, client/src/app/project-form/project-form.component.ts, client/src/app/shared/components/data-table/data-table.component.spec.ts, client/src/app/shared/services/ingest.service.ts
ebi-ait/dcp-ingest-central#109
=> Do not directly update the validationState and use the /draft endpoint

client/src/app/project-form/layout.ts, client/src/app/project-form/project-ingest-schema.json, client/src/app/project-registration/project-id/project-id.component.html, client/src/app/project-registration/project-id/project-id.component.spec.ts, client/src/app/project-registration/project-id/project-id.component.ts, client/src/app/project-registration/project-registration-form/project-reg-layout.ts
Related to [150](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/150)
=> Add form element to add organ

client/src/app/project-form/project-form.component.ts
Relates to [this task](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/154)
=> Remove request that will be done in core

client/src/app/metadata-details-dialog/metadata-details-dialog.component.ts
Relates to https://github.com/ebi-ait/ingest-core/pull/58
=> Remove code that is now handled in core

client/src/app/submission/submit/submit.component.ts
ebi-ait/dcp-ingest-central#235
=> ebi-ait/dcp-ingest-central#235

client/src/app/submission/submit/submit.component.html, client/src/app/submission/submit/submit.component.ts
Fixes [#160](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/160)
Is dependant on:
PR in core: https://github.com/ebi-ait/ingest-core/pull/60
related PR:
In exporter: https://github.com/ebi-ait/ingest-exporter/pull/18
=> Issue#160: added option to export only metadata on the Submit screen

client/src/app/all-projects/all-projects.component.html, client/src/app/all-projects/all-projects.component.ts, client/src/app/metadata-schema-form/custom/select-list/select-list.component.html, client/src/app/metadata-schema-form/custom/select-list/select-list.component.ts, client/src/app/metadata-schema-form/metadata-field-types/base-input/base-input.component.ts, client/src/app/metadata-schema-form/metadata-schema-form.module.ts, client/src/app/my-projects/my-projects.component.html, client/src/app/my-projects/my-projects.component.ts, client/src/app/project-form/project-ingest-schema.json, client/src/app/project-registration/admin-area/admin-area.component.html, client/src/app/project-registration/admin-area/admin-area.component.ts, client/src/app/project-registration/project-registration.module.ts, client/src/app/project-registration/wrangling-priority-input/wrangling-priority-input.component.html, client/src/app/project-registration/wrangling-priority-input/wrangling-priority-input.component.ts, client/src/app/shared/components/data-table/data-table.component.ts, client/src/app/shared/components/project-list/project-list.component.html, client/src/app/shared/components/project-list/project-list.component.ts, client/src/app/shared/models/project.ts
This PR needs changes in core: https://github.com/ebi-ait/ingest-core/pull/70
**Changes:**
For ticket ebi-ait/dcp-ingest-central#313 :
- Adding primary wrangler and wrangling status in project list
For ticket ebi-ait/dcp-ingest-central#317 :
- Applied Enrique and Gab's feedback
**Screenshots:**
=> Adding primary wrangler and wrangling status in project list

client/src/app/project-form/layout.ts, client/src/app/project-form/project-ingest-schema.json, client/src/app/project-registration/project-registration-form/project-reg-layout.ts
ebi-ait/dcp-ingest-central#344
=> Added cell count when viewing and editing the project

client/src/app/project-form/project-form.component.html, client/src/app/project-form/project-form.component.ts, client/src/app/project-summary/project-summary.component.html, client/src/app/project-summary/project-summary.component.ts
Changes:
- The `config` variable is created in an async block. We should wait while that variable properly created to be able to use it, otherwise we get an `undefined` value that would cause an error.
=> The config must be defined before loading metadata form component

client/src/app/shared/components/data-table/data-table.component.html, client/src/app/shared/components/data-table/data-table.component.ts, client/src/app/shared/shared.module.ts, client/src/app/shared/utils.ts
Changes:
- Revert URL check to the previous code as using a regular expression was too expensive
- Use `ng-template` for else condition
=> Fix unresponsive UI

client/src/app/project-form/project-form.component.spec.ts, client/src/app/project-form/project-form.component.ts
Changes:
- Just a small fix for the null error when trying to edit a suggested project
=> Fix null error on the content field of project resource

client/src/app/metadata-schema-form/metadata-form/metadata-form.component.spec.ts, client/src/app/metadata-schema-form/metadata-form/metadata-form.component.ts
ebi-ait/dcp-ingest-central#378
Changes:
- Display a suggested project properly on the UI in `View mode`
=> Fix null error in case of null project content

client/src/app/all-projects/all-projects.component.css, client/src/app/all-projects/all-projects.component.html, client/src/app/all-projects/all-projects.component.ts, client/src/app/project-form/project-ingest-schema.json, client/src/app/shared/data-sources/metadata-data-source.ts, client/src/app/shared/services/ingest.service.ts
closes dcp-313
relevant PR for core: https://github.com/ebi-ait/ingest-core/pull/75
=> ebi-ait/dcp-ingest-central#313: Added wrangling status and wrangler filters to `All Projects` page

client/src/app/all-projects/all-projects.component.html, client/src/app/all-projects/all-projects.component.ts, client/src/app/shared/data-sources/metadata-data-source.ts, client/src/app/shared/data-sources/project-data-source.ts, client/src/app/shared/services/ingest.service.ts
Relates to #103 
- Fixes issue where clearing search returns no results
- Introduces a ProjectDataSource which cleans up the use of QueryData in the data sources and removes some logic from the component
- Names some methods a bit better
- Removes unneccesary code
=> Filter projects cleanup

client/src/app/project-create-edit/components/contact-field-group/contact-field-group.component.ts
corresponding ticket: [dcp 225](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/225)
=> ebi-ait/dcp-ingest-central#225: moved contributor name field to be first form field

client/src/app/shared/models/submissionEnvelope.ts, client/src/app/submission/submission.component.spec.ts, client/src/app/submission/submission.component.ts
=> Reset error banners when there is no submission errors

client/src/app/shared/components/upload/upload.component.ts
=> Clear file input when done

src/app/app.module.ts, src/app/shared/shared.module.ts
ebi-ait/dcp-ingest-central#566
=> dcp-566 Fix missing file input in the Spreadsheet tab in submission page

src/app/project-summary/project-summary.component.ts, src/app/project/project.component.ts, src/app/projects/services/project-cache.service.spec.ts, src/app/shared/components/submission-state/submission-state.component.html, src/app/shared/components/submission-state/submission-state.component.ts, src/app/shared/constants.ts, src/app/shared/models/metadata-document.ts, src/app/submission/components/metadata-list/metadata-list.component.html, src/app/submission/components/metadata-list/metadata-list.component.ts, src/app/submission/components/validation-summary/validation-summary.component.html, src/app/submission/pages/submission.component.html, src/app/submission/pages/submission.component.ts
dcp-546
- Formats and shows the new submission states for graph validation (removing need for `graphValidationState`
- Allows graph validation whenever submission is `METADATA_VALID`
- Refactors a bit to move all of the submission states to enums
=> Dcp 456 states

src/app/submission/components/metadata-list/metadata-list.component.html, src/app/submission/components/validation-summary/validation-summary.component.html, src/app/submission/pages/submission.component.ts
=> Add back summary for graph validation errors

src/app/project/project.component.html, src/app/project/project.component.ts, src/app/shared/components/upload/upload.component.css, src/app/shared/components/upload/upload.component.html, src/app/shared/components/upload/upload.component.ts, src/app/shared/services/broker.service.spec.ts, src/app/shared/services/broker.service.ts, src/app/shared/shared.module.ts
ebi-ait/dcp-ingest-central#549
=> DCP 549: Overwrite project metadata on spreadsheet upload

src/app/shared/models/fetch-submission-data-options.ts, src/app/shared/services/ingest.service.spec.ts, src/app/shared/services/ingest.service.ts, src/app/submission/pages/submission.component.ts
- Fixes the bug
- Adds some tests to ensure this doesn't happen again
=> Fix issue where page and size were not getting passed through

src/app/projects/pages/autofill-project-form/autofill-project-form.component.ts, src/app/projects/services/autofill-project.service.ts, src/app/shared/services/ingest.service.spec.ts, src/app/shared/services/ingest.service.ts
Fixes for https://github.com/ebi-ait/dcp-ingest-central/issues/509
1. Use Europe PMC to check DOI Exists
2. If the DOI does not exist the wrangler email link includes the searched for DOI
- ![Screenshot 2022-01-20 at 14 02 43](https://user-images.githubusercontent.com/13031259/150353836-d7847304-e32f-4085-8f3f-a15f94aadc2e.png)
3. If the DOI is already used in a project (or more), a link to the project is given in the error message:
- ![Screenshot 2022-01-20 at 14 03 33](https://user-images.githubusercontent.com/13031259/150353977-f9489740-78c2-4e5e-8c64-4f604dba5064.png)
- ![Screenshot 2022-01-20 at 14 03 59](https://user-images.githubusercontent.com/13031259/150353993-1f1a556b-0155-4031-ac13-c7288d706c3f.png)
4. When Europe PMC doesn't provide all the properties we now use what we can …
=> DCP 509: DOI Validation

src/app/projects/pages/autofill-project-form/autofill-project-form.component.html, src/app/projects/pages/autofill-project-form/autofill-project-form.component.ts
dcp-509 
- Adds frontend regex validation of DOI
- Adds a loading state
- Refactors a bit to bring control of output to the primary observable
=> Address Issues with validation of DOI autofill

src/app/http-interceptors/http-error-interceptor.ts, src/app/shared/components/upload/upload.component.html, src/app/shared/models/submissionEnvelope.ts, src/app/shared/services/broker.service.ts, src/app/submission/components/spreadsheet-tab-details/spreadsheet-tab-details.component.html, src/app/submission/components/spreadsheet-tab-details/spreadsheet-tab-details.component.spec.ts, src/app/submission/components/spreadsheet-tab-details/spreadsheet-tab-details.component.ts, src/app/submission/pages/submission.component.html, src/app/submission/pages/submission.component.spec.ts, src/app/submission/pages/submission.component.ts, src/app/submission/submission.module.ts
ebi-ait/dcp-ingest-central#600
Please check miro for screenshots: https://miro.com/app/board/uXjVOX88PlI=/
=> DCP 600 - Make downloading of spreadsheet async 

src/app/projects/components/contact-field-group/contact-field-group.component.html, src/app/projects/components/contact-field-group/contact-field-group.component.spec.ts, src/app/projects/components/contact-field-group/contact-field-group.component.ts, src/app/projects/projects.module.ts
=> Put contributors in a table view when in view mode

src/app/shared/services/broker.service.spec.ts, src/app/shared/services/broker.service.ts
=> DCP 628: Fix broker parsing of error

src/app/shared/services/ingest.service.ts, src/app/submission/components/metadata-new/metadata-new.component.spec.ts, src/app/submission/components/metadata-new/metadata-new.component.ts
Zenhub: dcp-750
GitHub: ebi-ait/dcp-ingest-central#750
Depends on: https://github.com/ebi-ait/ingest-core/pull/125
=> dcp-750 Ingest Core now creates project links when creating metadata on submission

src/app/submission/components/files/files.component.html, src/app/submission/components/files/files.component.ts, src/app/submission/pages/submission.component.html, src/app/submission/pages/submission.component.ts
This reverts commit 0938ce1bee35443f9eb5f965b0e4e36964e3c4e6.
Relates to https://github.com/ebi-ait/ingest-core/pull/126
=> Revert "dcp-730 disable editing if is in metadata validating too"

src/app/projects/components/audit-log/audit-log.component.html, src/app/projects/components/audit-log/audit-log.component.spec.ts, src/app/projects/components/audit-log/audit-log.component.ts, src/app/projects/models/audit-log.ts, src/app/projects/pages/project/project.component.html, src/app/projects/pages/project/project.component.ts, src/app/projects/projects.module.ts
depends on: https://github.com/ebi-ait/ingest-core/pull/129/
=> dcp-547 project wrangling status history

src/app/my-projects/my-projects.component.ts, src/app/projects/components/admin-area/admin-area.component.html, src/app/projects/components/admin-area/admin-area.component.ts, src/app/projects/components/project-filters/project-filters.component.html, src/app/projects/components/project-filters/project-filters.component.spec.ts, src/app/projects/components/project-filters/project-filters.component.ts, src/app/projects/pages/all-projects/all-projects.component.ts, src/app/projects/schemas/project-ingest-schema.json, src/app/shared/components/project-list/project-list.component.ts, src/app/shared/models/project.ts, src/environments/environment.ts
PR for core: https://github.com/ebi-ait/ingest-core/pull/134
=> ebi-ait/dcp-ingest-central#663: added wranglingLabels field to project

src/app/submission-list/submission-list.component.html, src/app/submission-list/submission-list.component.ts
supersedes: #177
GitHub: ebi-ait/dcp-ingest-central#767
ZenHub: dcp-767
=> dcp-767 Remove upload submission button

.dockerignore, src/assets/guide-markdown/data-requirements.md
with Gabby's fixes of 10/1
dcp-717
ebi-ait/dcp-ingest-central#717
=> dcp-717 submission guide 1st draft from Gabby

src/app/projects/components/project-filters/project-filters.component.html, src/app/projects/components/project-filters/project-filters.component.spec.ts, src/app/projects/components/project-filters/project-filters.component.ts
dcp-852
ebi-ait/dcp-ingest-central#852
=> dcp-852 fix emptying of search field after pressing enter

src/app/my-projects/my-projects.component.ts, src/app/projects/components/admin-area/admin-area.component.html, src/app/projects/components/admin-area/admin-area.component.ts, src/app/projects/components/project-filters/project-filters.component.html, src/app/projects/components/project-filters/project-filters.component.spec.ts, src/app/projects/components/project-filters/project-filters.component.ts, src/app/projects/pages/all-projects/all-projects.component.ts, src/app/projects/schemas/project-ingest-schema.json, src/app/shared/components/project-list/project-list.component.ts, src/app/shared/models/project.ts
dcp-911
ebi-ait/dcp-ingest-central#911
=> dcp-911 project networks fixes

src/app/projects/schemas/project-ingest-schema.json
[dcp-911]
https://github.com/ebi-ait/dcp-ingest-central/issues/911
=> dcp-911 adding Blood to the enum networks

src/app/metadata-schema-form/metadata-field-types/ontology-base/ontology-base.component.ts, src/app/metadata-schema-form/metadata-field-types/ontology-base/ontology-search.md, src/app/metadata-schema-form/metadata-field-types/ontology-list-input/ontology-list-input.component.ts, src/app/shared/models/ols.ts, src/app/shared/services/ontology.service.spec.ts, src/app/shared/services/ontology.service.ts
dcp-881
ebi-ait/dcp-ingest-central#881
=> dcp-881 fix ontology term text box suggestions

.gitlab-ci.yml, Dockerfile, src/app/metadata-schema-form/models/json-schema-property.ts, src/app/projects/components/data-use-restriction-group/data-use-restriction-group.component.ts
This PR addresses the integration of Snyk for security scanning in our CI/CD pipeline. The changes involve updating the Dockerfile and .gitlab-ci.yml to properly handle the Snyk token.
- **Dockerfile**:
- Introduced ARG `SNYK_TOKEN`.
- Set the Snyk token as an environment variable to be used during the build process.
- **.gitlab-ci.yml**:
- Modified the build job to pass the Snyk token as a build argument using `--build-arg SNYK_TOKEN=$SNYK_TOKEN`.
Ensure that the Snyk token is securely stored and managed within GitLab CI/CD variables.
https://github.com/ebi-ait/dcp-ingest-central/issues/1011
=> Feature/dcp-1011 Snyk Token Handling
