- .gitignore
- client/angular.json
- client/karma.conf.js
- client/src/app/aai/aai.module.ts
- client/src/app/aai/aai.service.spec.ts
- client/src/app/aai/aai.service.ts
- client/src/app/aai/auth-guard.service.ts
- client/src/app/aai/oidc-interceptor.ts
- client/src/app/app.module.ts
- client/src/app/app.routes.ts
- client/src/app/core/authentication.service.spec.ts
- client/src/app/core/authentication.service.ts
- client/src/app/core/security.data.ts
- client/src/app/core/security.module.ts
- client/src/app/login/login.component.spec.ts
- client/src/app/registration/registration.component.css
- client/src/app/registration/registration.component.html
- client/src/app/registration/registration.component.spec.ts
- client/src/app/registration/registration.component.ts
- client/src/app/submitter/welcome/welcome.component.spec.ts
- client/tsconfig.json
Modified the sign-in procedure to check if the User has a registered Account in Ingest Core. For Users that have yet to sign-up, the UI redirects them to the registration page.
The registration page refers to some terms and condition that are yet to be provided.
> Updated sign-in to involve registration for first time Users

- client/src/app/shared/components/project-view/project-view.component.html
- client/src/app/shared/metadata-form/fields/date-input/date-input.component.ts
- client/src/app/shared/metadata-form/fields/input/input.component.html
- client/src/app/shared/metadata-form/fields/metadata-field.directive.ts
- client/src/app/shared/metadata-form/fields/ontology-input/ontology-input.component.html
- client/src/app/shared/metadata-form/fields/ontology-input/ontology-input.component.spec.ts
- client/src/app/shared/metadata-form/fields/ontology-input/ontology-input.component.ts
- client/src/app/shared/metadata-form/fields/ontology-input/ontology.ts
- client/src/app/shared/metadata-form/fields/text-list-input/text-list-input.component.ts
- client/src/app/shared/metadata-form/fields/vf-input/vf-input.component.html
- client/src/app/shared/metadata-form/metadata-form-helper.spec.ts
- client/src/app/shared/models/ols.ts
- client/src/app/shared/services/ontology.service.ts
- client/src/app/shared/shared.module.ts
- client/src/app/submission/metadata/metadata.component.html
- client/src/environments/environment.dev.ts
- client/src/environments/environment.env.ts
- client/src/environments/environment.env.ts.template
- client/src/environments/environment.integration.ts
- client/src/environments/environment.prod.ts
- client/src/environments/environment.staging.ts
- client/src/environments/environment.testing.ts
- client/src/environments/environment.ts
Enhancement:
- Added ontology input field
Fixes:
- Clearing out of string list fields
- Set default date value to now
- Avoid shrinking of view and table inside mat card
- Display description if guidelines attribute is not in schema
Related ingest-kube-deployment PR to add ontology url in the UI deployment config: https://github.com/ebi-ait/ingest-kube-deployment/pull/2
> Added ontology input field

- client/src/app/metadata-schema-form/metadata-field-types/enum-list-input/enum-list-input.component.ts
- client/src/app/metadata-schema-form/metadata-field-types/input/input.component.ts
- client/src/app/metadata-schema-form/metadata-field-types/ontology-list-input/ontology-list-input.component.ts
- client/src/app/shared/guards/wrangler-or-owner.guard.ts
Resolves [#144](https://github.com/ebi-ait/hca-ebi-dev-team/issues/144)
- Owner guard would not retrieve project info from url with path params, fixed.
- The confirmation dialog when removing an item from select many would remove the item from the screen but not the data if you clicked cancel. the confirmation gets in the way of user flow, so removed it.
Deployed to [Dev](https://ui.ingest.dev.archive.data.humancellatlas.org)
> User Guard and Form Confirmation Bug Fixes

- client/src/app/aai/aai.service.ts
- client/src/app/login/login.component.ts
- client/src/app/shared/guards/user-is-logged-in.guard.ts
- client/src/app/shared/guards/user-is-wrangler.guard.ts
- client/src/app/shared/guards/wrangler-or-owner.guard.ts
Implements ticket [#195](https://github.com/ebi-ait/hca-ebi-dev-team/issues/195)
Deployed to [Dev](https://ui.ingest.dev.archive.data.humancellatlas.org)
- Preserve the user's destination if interrupted by the login page.
- Raise a message when the user attempts to access resource they are not authorised to see:
- Previously would simply fail to the home screen with no message.
- Contributor's accessing wrangler pages.
- Contributor's accessing other contributor's projects.
> Feature: Login Redirect

- client/src/app/project/project.component.html
[commit 49c7e29](https://github.com/ebi-ait/ingest-ui/commit/49c7e29649838cf2655c508d85be357c90f7890e) introduced a bug where the upload button is above the project view and the upload control is below it.
This PR remedies that bug.
> Upload control should be above project.

- client/src/app/shared/components/upload/upload.component.html
- client/src/app/shared/components/upload/upload.component.ts
Implementation for [#201](https://github.com/ebi-ait/hca-ebi-dev-team/issues/201):
- Add possibility for the user to select if the uploaded spreadsheet should create a new submission or update an existing one.
Deployed to [Dev](https://dev.contribute.data.humancellatlas.org) for review.
> Add possibility to select whether the uploaded submission new or an update

- client/src/app/project-form/project-form.component.ts
- client/src/app/project-registration/project-registration-form/project-registration-form.component.ts
- client/src/app/shared/services/ingest.service.ts
Updated both the contributor and wrangler views of project registration to use partial updates mainly to avoid the system from sending more notifications than necessary.
> Partial Project updates for Project registration

- client/src/app/app.component.ts
Part of the Elixir login/register flow review ([#298](https://app.zenhub.com/workspaces/ingest-dev-5cfe1cb26482e537cf35e8d1/issues/ebi-ait/hca-ebi-dev-team/298)), there's no need for an additional confirm popup since we're taken to the Elixir Logout Requested confirm page to confirm logout (which we can't skip!)
> Removed confirm popup

- client/src/app/project/project.component.html
- client/src/app/project/project.component.ts
- client/src/app/shared/services/ingest.service.ts
- client/src/app/submission-list/submission-list.component.ts
This should populate the project title in the submissions dashboard even if the project is not created by the submission.
> Display the related project linked to a submission

- client/src/app/shared/constants.ts
- client/src/app/shared/models/data-source.ts
- client/src/app/shared/models/paginatedEndpoint.ts
- client/src/app/shared/services/ingest.service.ts
- client/src/app/submission/files/files.component.html
- client/src/app/submission/files/files.component.ts
- client/src/app/submission/metadata-data-source.ts
- client/src/app/submission/metadata-list/metadata-list.component.html
- client/src/app/submission/metadata-list/metadata-list.component.ts
- client/src/app/submission/submission.component.html
- client/src/app/submission/submission.component.scss
- client/src/app/submission/submission.component.ts
This PR allows for filtering by file validation error type (invalid metadata, invalid file, file missing) but it also does a fair bit of refactoring to extract data gathering from the component. This separates the concerns a bit and should make it easier to incorporate this into project view when we can.
Here's a breakdown of the changes:
- Created a `PaginatedDataSource`
- This is responsible for gathering metadata, performing polling, pagination, and sorting
- This currently sites in the `submission` directory but I think should be moved to `shared` as the logic is reusable.
- Created a `MetadataDataSource`
- This extends `PaginatedDataSource` and adds filtering by state and file validation state
- This also currently sits in the `submission` directory but I think should be moved to …
> Allow for filtering by file validation error

- client/src/app/project-form/layout.ts
I didn't realise there were two forms!
Relates to #77
> Fix typo that caused organ form element not to show in projects/new

- client/package-lock.json
- client/package.json
- client/src/app/metadata-details-dialog/metadata-details-dialog.component.html
- client/src/app/metadata-details-dialog/metadata-details-dialog.component.ts
- client/src/app/shared/services/ingest.service.ts
- client/src/app/submission/metadata-list/metadata-list.component.ts
File metadata can't be updated in the UI. It seems that all other fields are being sent as part of the payload and the PATCH /files/id endpoint is throwing a HTTP 400 (Bad request) error. This is not happening for other metadata types. I need to check how the file metadata json is being serialised vs other metadata in Core. But this change in the UI fixes it.
ebi-ait/dcp-ingest-central#77
> Only send the content object when PATCHing

- client/src/app/app.module.ts
- client/src/app/metadata-schema-form/metadata-form/metadata-form.component.ts
- client/src/app/project-registration/autofill-project-form/autofill-project-form.component.html
- client/src/app/project-registration/autofill-project-form/autofill-project-form.component.ts
- client/src/app/project-registration/project-registration-form/project-registration-form.component.html
- client/src/app/project-registration/project-registration-form/project-registration-form.component.ts
- client/src/app/project-registration/services/cache-project.service.ts
- client/src/app/project-registration/services/project-cache.service.ts
- client/src/environments/environment.dev.ts
- client/src/environments/environment.env.ts
- client/src/environments/environment.prod.ts
- client/src/environments/environment.staging.ts
- client/src/environments/environment.ts
- prepare_artifact.sh
While registering a new project, the project will get autosaved to browser local storage every 10 seconds, after every form change by user.
The key for the project will be `{user email address}-project` and the value will be the stringy-fied project object.
This autosaved project in the browser local storage will get deleted when the project gets saved in the ingest db and the option to `restore your unsaved project` will only be available if there is an unsaved project in the local storage
> Added autosave to local storage for project registration

- prepare_artifact.sh
reverting this change: https://github.com/ebi-ait/ingest-ui/pull/89/commits/2ed0cde8ca60e0d011df677f77f64ee52d30bf50, as the autosave timer is constant for all envs
> ebi-ait/dcp-ingest-central#19: hotfix: revert changes to prepare_artifact.sh

- client/src/app/shared/utils.spec.ts
- client/src/app/shared/utils.ts
ebi-ait/dcp-ingest-central#353
Changes:
- If the table cell value does not start with `http` then it won't appear as a URL on the screen.
> Show ontology value correctly

- client/src/app/project-create-edit/components/contact-field-group/contact-field-group.component.ts
Adds the contributor name back to the form as pointed out by @gabsie 
For dcp-225
> Add back contributor name

- client/src/app/metadata-schema-form/custom/vf-input/vf-input.component.html
- client/src/app/metadata-schema-form/custom/vf-input/vf-input.component.ts
- client/src/app/metadata-schema-form/models/metadata-form-helper.ts
- client/src/app/metadata-schema-form/models/metadata.ts
- client/src/app/project-create-edit/components/project-metadata-form/layout.ts
- client/src/app/project-create-edit/components/publication-field-group/publication-field-group.component.ts
- client/src/app/project-create-edit/schemas/project-metadata-schema.json
dcp-424 and dcp-430
- Adds official_hca_publication checkbox to the project registration form
- Changes behaviour of boolean inputs:
- Boolean inputs can be `true`, `false`, or `undefined` (corresponding contributor) or if they're required fields they can only be `true` of `false` (official hca publication)
- This removes the `isRequired` validator from boolean fields since that will fail if the value is `false`
- It also removes the required asterisk marker in the UI on boolean fields since all boolean fields can be `false` as well (unticked)
- If a boolean field is required then it will be set to `false` by default thus never being able to get to `undefined`
- If a boolean field is not required then it will be `undefined` by default but as soon as it is touched it will only be able to …
> Add HCA publication

- client/src/app/metadata-schema-form/metadata-form.service.spec.ts
- client/src/app/metadata-schema-form/metadata-form.service.ts
dcp-458
Not the most elegant solution but it works.
Deep searches through the form data to find any key that is "publication" or "publications" and removes and publications that only have `official_hca_publication` set. 
In the project registration form, since a publication is by default "added", the user will still have to delete the publication using the controls if they wish to proceed with registering due to the front-end validation. I believe this is desired as in most cases, there will be a publication
> Clean publications from form if empty

- src/app/submission/submission.component.html
- src/app/submission/submission.component.ts
dcp-535
- Adds a "Requested" state
- User cannot request another graph validation while in "Requested" state
- Fixes bug where UI would go from "Pending" -> "Validating" -> "Pending" -> "Validating"
> dcp-535 add requested state

- src/app/submission/submission.component.html
- src/app/submission/submission.component.ts
dcp-508
Shows a list of affected entities in the validate tab. Later on, in dcp-507, these messages can be bought in line with the effected entitites
> Show list of affected entitites

- src/app/shared/components/alert/alert.component.ts
- src/app/shared/models/alert.ts
- src/app/shared/services/alert.service.ts
- src/app/submission/components/submit/submit.component.ts
- src/app/submission/pages/submission.component.spec.ts
- src/app/submission/pages/submission.component.ts
dcp-607
- Reports the error from the server instead of a generic message
- Introduces the concept of "groups" to alerts
- Problem: Alerts were cleared whenever the submission was polled. This was done to refresh the alerts for submission errors. This also removed the alert that is needed here to report a server error when something goes wrong with submitting.
- The concept of "groups" allows alerts to be cleared on a group level. The alerts for submission errors are in their own group and cleared independently of any other alerts.
- This is an entirely backwards compatible new feature and does not change the API for previous alerts
- Remember this exists now :) Might be useful in other places too
> Report error from server

- src/app/metadata-schema-form/metadata-form/metadata-form.component.spec.ts
- src/app/metadata-schema-form/metadata-form/metadata-form.component.ts
- src/app/metadata-schema-form/models/metadata-form-config.ts
- src/app/metadata-schema-form/models/metadata-registry.ts
- src/app/project-summary/project-summary.component.ts
- src/app/projects/components/project-metadata-form/project-metadata-form.component.ts
- src/app/projects/components/wrangler-list-input/wrangler-list-input.component.ts
fixes for: https://github.com/ebi-ait/dcp-ingest-central/issues/620
- undefined
- null
- true
- false
- empty array
- `config.cleanAttributes = ['content'];`
> DCP 620: Unassign Wrangler

- src/app/projects/components/admin-area/admin-area.component.ts
- src/app/projects/components/contact-field-group/contact-field-group.component.html
- src/app/projects/components/contact-field-group/contact-field-group.component.ts
dcp-574
This hides the buttons when control metadata is `disabled === true`. The other form controls work like this
> Hide buttons when in read only mode

- src/app/submission/pages/submission.component.html
- src/app/submission/pages/submission.component.scss
- src/app/submission/pages/submission.component.ts
dcp-645
ebi-ait/dcp-ingest-central#645
**Changes:**
1. Tooltip in export/import icon button
2. Display linking progress - percentage done
3. Tooltip in the Spreadsheet tab label why disabled
4. Disable Validate tab when linking is in progress
5. Tooltip in the Validate tab label why disabled
5. Tooltip in the Submit tab why disabled
> dcp-645 disable spreadsheet tab when importing is ongoing

- src/app/projects/components/project-metadata-form/project-metadata-form.component.ts
- src/app/projects/pages/project/project.component.ts
- src/app/shared/models/submissionEnvelope.ts
- src/app/submission-list/submission-list.component.ts
- src/app/submission/components/files/files.component.html
- src/app/submission/components/files/files.component.ts
- src/app/submission/components/metadata-list/metadata-list.component.html
- src/app/submission/components/metadata-list/metadata-list.component.ts
- src/app/submission/components/metadata-new/metadata-new.component.ts
- src/app/submission/components/spreadsheet-tab-details/spreadsheet-tab-details.component.spec.ts
- src/app/submission/pages/submission.component.html
- src/app/submission/pages/submission.component.ts
dcp-730
- Shows the error messages from core if they exist. I think I have covered all of the places where errors could happen for this ticket but if you know of others, please say.
- Disables edit and delete buttons if submission is not `editable`
- disables and hides adding of metadata if not `editable`
> Show error messages from core if they exist and block action if in "ing" state

- src/app/projects/components/project-filters/project-filters.component.html
- src/app/projects/components/project-filters/project-filters.component.ts
ZenHub: dcp-792
GitHub: ebi-ait/dcp-ingest-central#792
Dependant on: ebi-ait/ingest-core#136
As a stakeholder, I want to get a list of projects which are Submitted but Catalogue=no, so that we can review and get them updated to show in the Catalog.
y
> dcp-792 Add HCA Catalogue to project query
